import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
  imprimante1,
  imprimante2,
  imprimante4,
  imprimante5,
  imprimante6,
  imprimante7,
  imprimante8,
  imprimante9,
  encre1,
  encre2,
  encre3,
  encre4,
  ruban1,
  ruban2,
  ruban3,
  ruban4,
  bac1,
  bac2,
  bac3,
  bac4,
  pdf1,
  IMPRIMANTE_PANTUM_CP2200DW,
  IMPRIMANTE_PANTUM_BM5100FDW,
  IMPRIMANTE_PANTUM_M6609N,
  IMPRIMANTE_PANTUM_P3300DN,
  IMPRIMANTE_PANTUM_P3300DW,
  IMPRIMANTE_PANTUM_P2509W,
  IMPRIMANTE_PANTUM_BP5100DN,
  IMPRIMANTE_PANTUM_M6559N,
  IMPRIMANTE_PANTUM_P2509,
  hp1,
  hp2,
  hp3,
  ricoh1,
  ricoh2,
  ricoh3,
  ricoh4,
  ricoh5,
  espson1,
  espson2,
} from "../assets/images/index";

import "./style.css";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img : {spfOne},
    productName: "Classic Denim Jacket",
    price: "35.00",
    color: "Blue Wash",
    badge: true,
    des: "Vintage-style denim jacket with button closure. Perfect layering piece for casual outfits. Features two chest pockets and a comfortable regular fit.",
    cat: "Jackets",
  },
  {
    _id: "202",
    img : {spfOne },
    productName: "Wool Blend Overcoat",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Sophisticated wool blend overcoat with elegant design. Double-breasted style with notch lapels. Perfect for business and formal occasions.",
    cat: "Coats",
  },
  {
    _id: "203",
    img : {spfOne}  ,
  productName: "Graphic Print T-Shirt",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Trendy graphic t-shirt with artistic print. Made from soft cotton blend for all-day comfort. Available in various color combinations.",
    cat: "T-Shirts",
  },
  {
    _id: "204",
    img : {spfOne},
    productName: "Leather Biker Jacket",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Premium leather biker jacket with asymmetric zipper. Features multiple pockets and adjustable belt. Timeless style for edgy looks.",
    cat: "Jackets",
  },
  {
    _id: "205",
    img : {spfOne},
    productName: "Flannel Plaid Shirt",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Comfortable flannel shirt in classic plaid pattern. Soft brushed cotton for warmth. Perfect for casual weekends and layering.",
    cat: "Shirts",
  },
  {
    _id: "206",
    img : {spfOne},
    productName: "Bomber Jacket",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Contemporary bomber jacket with ribbed cuffs and hem. Lightweight yet durable design. Features front zip closure and side pockets.",
    cat: "Jackets",
  },
  {
    _id: "207",
    img : {spfOne},
    productName: "Striped Knit Sweater",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Cozy striped sweater with crew neck design. Soft knit fabric for comfort. Perfect for transitional weather and layering.",
    cat: "Sweaters",
  },
  {
    _id: "208",
    img : {spfOne},  
     productName: "Zip-Up Hoodie",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Athletic zip-up hoodie with fleece lining. Features kangaroo pockets and adjustable drawstring. Ideal for casual wear and workouts.",
    cat: "Hoodies",
  },
  {
    _id: "209",
    img : {spfOne},
        productName: "Formal Dress Shirt",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Crisp formal dress shirt with spread collar. Wrinkle-resistant fabric for professional appearance. Perfect for office and formal events.",
    cat: "Shirts",
  },
  {
    _id: "210",
    img : {spfOne},
    productName: "Classic Polo Shirt",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Timeless polo shirt in pique cotton. Features ribbed collar and cuffs. Versatile piece for smart casual occasions.",
    cat: "Polo Shirts",
  },
  {
    _id: "211",
    img : {spfOne},
    productName: "Long Sleeve Henley",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Casual henley shirt with button placket. Soft cotton fabric for all-day comfort. Great for layering or wearing alone.",
    cat: "T-Shirts",
  },
  {
    _id: "212",
    img : {spfOne},   productName: "Turtleneck Sweater",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Elegant turtleneck sweater in fine knit. Classic silhouette with modern fit. Perfect for cold weather styling.",
    cat: "Sweaters",
  },
  {
    _id: "213",
    img : {spfOne},
    productName: "Genuine Leather Belt",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "High-quality leather belt with metal buckle. Available in multiple colors. Essential accessory for any wardrobe.",
    cat: "Accessories",
  },
  {
    _id: "214",
    img : {spfOne},
    productName: "Casual Watch",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Stylish casual watch with leather strap. Water-resistant design with clean dial. Perfect everyday timepiece.",
    cat: "Accessories",
  },
  {
    _id: "215",
    img : {spfOne},
    productName: "Winter Scarf",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Warm winter scarf in soft wool blend. Long length for multiple styling options. Available in various patterns.",
    cat: "Accessories",
  },
  {
    _id: "216",
    img : {spfOne},
    productName: "Baseball Cap",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Classic baseball cap with adjustable strap. Structured crown with curved brim. Perfect for casual everyday wear.",
    cat: "Accessories",
  },
  {
    _id: "217",
    img : {spfOne},
    productName: "Canvas Backpack",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Durable canvas backpack with multiple compartments. Padded straps for comfort. Ideal for school, work, or travel.",
    cat: "Bags",
  },
  {
    _id: "219",
    img : {spfOne},
    productName: "Messenger Bag",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Professional messenger bag with laptop compartment. Adjustable shoulder strap. Perfect for commuting and business.",
    cat: "Bags",
  },
  {
    _id: "220",
    img : {spfOne} ,  productName: "Duffle Bag",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Spacious duffle bag for travel and gym. Water-resistant fabric with reinforced handles. Multiple pockets for organization.",
    cat: "Bags",
  },
  {
    _id: "221",
    img : {spfOne}, productName: "Canvas Tote Bag",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Versatile canvas tote bag with sturdy handles. Large capacity for shopping or everyday use. Eco-friendly and durable.",
    cat: "Bags",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: "201",
    img : {spfOne},
    productName: "Classic Denim Jacket",
    price: "89.99",
    color: "Blue",
    badge: true,
    brand: "Urban Style",
    des: "Premium denim jacket with vintage wash - 100% cotton - Button closure - Two chest pockets - Regular fit - Machine washable - Perfect for casual and semi-formal occasions",
    cat: "Jackets",
    pdf: "pdf1",
    ficheTech: [
      { label: "Material", value: "100% Cotton Denim" },
      { label: "Size Range", value: "XS to XXL" },
      { label: "Care Instructions", value: "Machine wash cold" },
    ],
  },
  {
    _id: "202",
    img : {spfOne},
    productName: "Premium Cotton T-Shirt",
    price: "29.99",
    color: "White",
    badge: true,
    brand: "ComfortWear",
    des: "Essential crew neck t-shirt - 100% organic cotton - Pre-shrunk fabric - Reinforced shoulder seams - Available in multiple colors - Breathable and lightweight",
    cat: "T-Shirts",
    pdf: "pdf1",
    ficheTech: [
      { label: "Material", value: "100% Organic Cotton" },
      { label: "Weight", value: "180 GSM" },
      { label: "Fit", value: "Regular Fit" },
    ],
  },
  {
    _id: "203",
    img : {spfOne},
    productName: "Slim Fit Dark Wash Jeans",
    price: "79.99",
    color: "Dark Blue",
    badge: true,
    brand: "DenimCo",
    des: "Modern slim fit jeans - Stretch denim for comfort - Five-pocket styling - Zip fly with button closure - Dark indigo wash - Perfect for everyday wear",
    cat: "Jeans",
    pdf: "pdf1",
    ficheTech: [
      { label: "Material", value: "98% Cotton, 2% Elastane" },
      { label: "Rise", value: "Mid-rise" },
      { label: "Leg Opening", value: "14 inches" },
    ],
  },
  {
    _id: "2005",
    img : {spfOne }, productName: "Pullover Hoodie",
    price: "65.00",
    color: "Grey",
    badge: true,
    brand: "StreetStyle",
    des: "Comfortable pullover hoodie - Soft fleece lining - Adjustable drawstring hood - Kangaroo pocket - Ribbed cuffs and hem - Unisex design - Perfect for layering",
    cat: "Hoodies",
    pdf: "pdf1",
    ficheTech: [
      { label: "Material", value: "80% Cotton, 20% Polyester" },
      { label: "Weight", value: "320 GSM" },
      { label: "Style", value: "Pullover" },
      { label: "Season", value: "Fall/Winter" },
      { label: "Care", value: "Machine wash warm" },
    ],
  },
  {
    _id: "20005",
    img : {spfOne},
    productName: "Classic Chino Pants",
    price: "59.99",
    color: "Khaki",
    badge: true,
    brand: "SmartCasual",
    des: "Versatile chino pants - Stretch cotton twill - Flat front design - Zip fly with button closure - Side and back pockets - Slim tapered leg - Perfect for work or weekend",
    cat: "Pants",
    pdf: "pdf1",
    ficheTech: [
      { label: "Material", value: "97% Cotton, 3% Spandex" },
      { label: "Fit", value: "Slim Tapered" },
      { label: "Inseam", value: "30-34 inches available" },
      { label: "Care", value: "Machine wash cold" },
    ],
  },
  {
    _id: "206",
    img : {spfOne},
    productName: "Formal Dress Shirt",
    price: "49.99",
    color: "White",
    badge: true,
    brand: "ExecutiveWear",
    des: "Professional dress shirt - Wrinkle-resistant fabric - Spread collar - French placket - Adjustable barrel cuffs - Slim fit design - Perfect for office or formal events",
    cat: "Shirts",
    pdf: "pdf1",
    ficheTech: [
      { label: "Material", value: "60% Cotton, 40% Polyester" },
      { label: "Collar Style", value: "Spread Collar" },
      { label: "Fit", value: "Slim Fit" },
      { label: "Care", value: "Machine wash, tumble dry low" },
      { label: "Features", value: "Wrinkle-resistant, Non-iron" },
    ],
  },
  {
    _id: "207",
    img : {spfOne},
    productName: "Pique Polo Shirt",
    price: "39.99",
    color: "Navy",
    badge: true,
    brand: "SportyChic",
    des: "Classic polo shirt - Cotton pique fabric - Ribbed collar and cuffs - Two-button placket - Side vents - Embroidered logo - Perfect for smart casual occasions",
    cat: "Polo Shirts",
    pdf: "pdf1",
    ficheTech: [
      { label: "Material", value: "100% Cotton Pique" },
      { label: "Weight", value: "200 GSM" },
      { label: "Fit", value: "Regular Fit" },
      { label: "Care", value: "Machine wash cold, hang dry" },
    ],
  },
  {
    _id: "208",
    img : {spfOne},
    productName: "Jogger Sweatpants",
    price: "45.00",
    color: "Black",
    badge: true,
    brand: "ActiveComfort",
    des: "Comfortable jogger sweatpants - Soft fleece interior - Elastic waistband with drawstring - Side pockets and back pocket - Tapered leg with ribbed cuffs - Perfect for lounging or light exercise",
    cat: "Pants",
    pdf: "pdf1",
    ficheTech: [
      { label: "Material", value: "70% Cotton, 30% Polyester" },
      { label: "Style", value: "Jogger/Tapered" },
      { label: "Pockets", value: "Side and back pockets" },
      { label: "Care", value: "Machine wash warm" },
    ],
  },
  {
    _id: "233",
    img : {spfOne},
    productName: "Utility Cargo Pants",
    price: "69.99",
    color: "Olive Green",
    badge: true,
    brand: "OutdoorGear",
    des: "Durable cargo pants - Multiple pockets including cargo pockets - Reinforced knees - Adjustable waist tabs - Straight leg fit - Water-resistant finish - Perfect for outdoor activities",
    cat: "Pants",
    pdf: "pdf1",
    ficheTech: [
      { label: "Material", value: "100% Cotton Canvas" },
      { label: "Pockets", value: "8 total pockets" },
      { label: "Treatment", value: "Water-resistant" },
    ],
  },
  {
    _id: "220",
    img : {spfOne},
    productName: "Genuine Leather Belt",
    price: "35.00",
    color: "Brown",
    badge: true,
    brand: "ClassicStyle",
    des: "Premium full-grain leather belt - Durable metal buckle - Width: 1.5 inches - Adjustable sizing - Perfect for formal and casual wear",
    cat: "Accessories",
    pdf: "pdf1",
  },
  {
    _id: "221",
    img : {spfOne},
    productName: "Wool Blend Scarf",
    price: "28.00",
    color: "Charcoal Grey",
    badge: true,
    brand: "WinterWarmth",
    des: "Soft wool blend scarf - Dimensions: 70 x 12 inches - Fringed ends - Lightweight yet warm - Available in multiple colors",
    cat: "Accessories",
    pdf: "pdf1",
  },
  {
    _id: "215",
    img : {spfOne},
    productName: "Athletic Crew Socks (6-Pack)",
    price: "22.00",
    color: "Multi-Color",
    badge: true,
    brand: "SportFoot",
    des: "Comfortable athletic socks - Moisture-wicking fabric - Arch support - Reinforced heel and toe - Pack of 6 pairs",
    cat: "Accessories",
    pdf: "pdf1",
  },
  {
    _id: "216",
    img : {spfOne},
    productName: "Baseball Cap",
    price: "25.00",
    color: "Black",
    badge: true,
    brand: "HeadGear",
    des: "Classic baseball cap - 100% cotton twill - Adjustable strap closure - Curved brim - Embroidered ventilation holes",
    cat: "Accessories",
    pdf: "pdf1",
  },
  {
    _id: "209",
    img : {spfOne},
    productName: "Leather Gloves",
    price: "45.00",
    color: "Black",
    badge: true,
    brand: "WinterHands",
    des: "Genuine leather gloves - Soft fleece lining - Touchscreen compatible fingertips - Elegant design",
    cat: "Accessories",
    pdf: "pdf1",
  },
  {
    _id: "210",
    img : {spfOne},
    productName: "Canvas Backpack",
    price: "75.00",
    color: "Navy Blue",
    badge: true,
    brand: "TravelGear",
    des: "Durable canvas backpack - Leather trim details - Multiple compartments - Padded laptop sleeve - Adjustable shoulder straps",
    cat: "Bags",
    pdf: "pdf1",
  },
  {
    _id: "211",
    img : {spfOne},    productName: "Leather Messenger Bag",
    price: "120.00",
    color: "Brown",
    badge: true,
    brand: "ExecutiveBags",
    des: "Professional messenger bag - Full-grain leather - Multiple interior pockets - Adjustable shoulder strap - Perfect for work",
    cat: "Bags",
    pdf: "pdf1",
  },
  {
    _id: "212",
    img : {spfOne}  ,  productName: "Bifold Wallet",
    price: "38.00",
    color: "Black",
    badge: true,
    brand: "Essentials",
    des: "Slim bifold wallet - Genuine leather - Multiple card slots - Bill compartment - RFID blocking technology",
    cat: "Accessories",
    pdf: "pdf1",
  },
  {
    _id: "213",
    img : {spfOne},
    productName: "Classic White Sneakers",
    price: "85.00",
    color: "White",
    badge: true,
    brand: "FootComfort",
    des: "Versatile low-top sneakers - Leather upper - Cushioned insole - Rubber outsole - Perfect for everyday wear",
    cat: "Footwear",
    pdf: "pdf1",
  },
  {
    _id: "214",
    img : {spfOne}  ,  productName: "Chelsea Boots",
    price: "135.00",
    color: "Tan",
    badge: true,
    brand: "BootCraft",
    des: "Classic Chelsea boots - Premium leather - Elastic side panels - Pull tabs - Durable rubber sole",
    cat: "Footwear",
    pdf: "pdf1",
  },
  {
    _id: "217",
    img : {spfOne  },productName: "Tailored Blazer",
    price: "159.99",
    color: "Navy",
    badge: true,
    brand: "ExecutiveWear",
    des: "Sophisticated tailored blazer - Wool blend fabric - Notch lapel - Two-button closure - Interior pockets - Fully lined - Perfect for business and formal occasions",
    cat: "Blazers",
    pdf: "pdf1",
    ficheTech: [
      { label: "Material", value: "70% Wool, 30% Polyester" },
      { label: "Fit", value: "Slim Fit" },
      { label: "Lining", value: "100% Polyester" },
      { label: "Care", value: "Dry clean only" },
    ],
  },
  {
    _id: "219",
    img : {spfOne},
    productName: "Athletic Shorts",
    price: "32.00",
    color: "Grey",
    badge: true,
    brand: "ActiveWear",
    des: "Performance athletic shorts - Moisture-wicking fabric - Elastic waistband with drawstring - Side pockets - Lightweight and breathable",
    cat: "Shorts",
    pdf: "pdf1",
  },
  {
    _id: "hp1",
    img : {spfOne} ,  productName: "Floral Summer Dress",
    price: "75.00",
    color: "Multi-Color Floral",
    badge: true,
    brand: "SummerStyle",
    des: "Beautiful floral summer dress - Lightweight cotton blend - V-neckline - Adjustable straps - Flowing A-line silhouette - Knee-length - Perfect for summer occasions and casual outings",
    cat: "Dresses",
    pdf: "pdf1",
    ficheTech: [
      { label: "Material", value: "95% Cotton, 5% Elastane" },
      { label: "Length", value: "Knee-length" },
      { label: "Style", value: "A-line" },
      { label: "Care", value: "Machine wash cold, hang dry" },
      { label: "Occasion", value: "Casual, Summer events" },
    ],
  },
  {
    _id: "hp2",
    img : {spfOne }, productName: "Silk Blouse",
    price: "89.99",
    color: "Cream",
    badge: true,
    brand: "ElegantStyle",
    des: "Luxurious silk blouse - 100% silk fabric - Button-front design - Long sleeves with button cuffs - Relaxed fit - Perfect for office or evening wear",
    cat: "Tops",
    pdf: "pdf1",
    ficheTech: [
      { label: "Material", value: "100% Silk" },
      { label: "Fit", value: "Relaxed" },
      { label: "Care", value: "Dry clean recommended" },
    ],
  },
  {
    _id: "hp3",
    img : {spfOne }, productName: "Pleated Midi Skirt",
    price: "55.00",
    color: "Black",
    badge: true,
    brand: "ChicWear",
    des: "Elegant pleated midi skirt - Flowy design - Elastic waistband - Midi length - Versatile styling options - Perfect for work or evening events",
    cat: "Skirts",
    pdf: "pdf1",
    ficheTech: [
      { label: "Material", value: "100% Polyester" },
      { label: "Length", value: "Midi (below knee)" },
      { label: "Waist", value: "Elastic" },
      { label: "Care", value: "Machine wash cold" },
    ],
  },
  {
    _id: "ricoh1",
    img : {spfOne} ,   productName: "Knit Cardigan",
    price: "68.00",
    color: "Beige",
    badge: true,
    brand: "CozyKnits",
    des: "Soft knit cardigan - Open front design - Long sleeves - Ribbed trim - Lightweight for layering - Perfect for transitional weather",
    cat: "Cardigans",
    pdf: "pdf1",
    ficheTech: [
      { label: "Material", value: "60% Cotton, 40% Acrylic" },
      { label: "Style", value: "Open front" },
      { label: "Fit", value: "Relaxed" },
      { label: "Care", value: "Hand wash cold, lay flat to dry" },
    ],
  },
  {
    _id: "ricoh2",
    img : {spfOne},
    productName: "Casual Jumpsuit",
    price: "95.00",
    color: "Olive",
    badge: true,
    brand: "UrbanChic",
    des: "Stylish casual jumpsuit - Adjustable straps - Elastic waist - Side pockets - Wide leg design - Perfect for weekend outings",
    cat: "Jumpsuits",
    pdf: "pdf1",
    ficheTech: [
      { label: "Material", value: "55% Linen, 45% Cotton" },
      { label: "Style", value: "Wide leg" },
      { label: "Closure", value: "Back zipper" },
    ],
  },
  {
    _id: "ricoh3",
    img : {spfOne},  productName: "Classic Trench Coat",
    price: "185.00",
    color: "Camel",
    badge: true,
    brand: "TimelessStyle",
    des: "Timeless trench coat - Water-resistant fabric - Double-breasted design - Belted waist - Storm flap - Fully lined - Perfect for rainy days",
    cat: "Coats",
    pdf: "pdf1",
    ficheTech: [
      { label: "Material", value: "100% Cotton with water-resistant coating" },
      { label: "Lining", value: "100% Polyester" },
      { label: "Length", value: "Knee-length" },
      { label: "Care", value: "Dry clean only" },
    ],
  },
  {
    _id: "ricoh4",
    img : {spfOne},
    productName: "Turtleneck Sweater",
    price: "72.00",
    color: "Burgundy",
    badge: true,
    brand: "WarmKnits",
    des: "Cozy turtleneck sweater - Soft knit fabric - Long sleeves - Ribbed trim - Relaxed fit - Perfect for cold weather",
    cat: "Sweaters",
    pdf: "pdf1",
    ficheTech: [
      { label: "Material", value: "50% Wool, 50% Acrylic" },
      { label: "Fit", value: "Relaxed" },
      { label: "Care", value: "Hand wash cold, dry flat" },
    ],
  },
  {
    _id: "ricoh5",
    img : {spfOne}  ,  productName: "High-Waist Yoga Leggings",
    price: "48.00",
    color: "Black",
    badge: true,
    brand: "ActiveFit",
    des: "Performance yoga leggings - High-waisted design - Moisture-wicking fabric - Four-way stretch - Hidden pocket - Squat-proof - Perfect for yoga and gym",
    cat: "Activewear",
    pdf: "pdf1",
    ficheTech: [
      { label: "Material", value: "88% Polyester, 12% Spandex" },
      { label: "Features", value: "Moisture-wicking, Four-way stretch" },
      { label: "Rise", value: "High-waisted" },
      { label: "Care", value: "Machine wash cold, tumble dry low" },
    ],
  },
  {
    _id: "espson1",
    img : {spfOne }, productName: "Sports Bra",
    price: "38.00",
    color: "Navy",
    badge: true,
    brand: "ActiveFit",
    des: "Supportive sports bra - Medium impact support - Moisture-wicking fabric - Removable pads - Racerback design - Perfect for workouts",
    cat: "Activewear",
    pdf: "pdf1",
    ficheTech: [
      { label: "Material", value: "80% Nylon, 20% Spandex" },
      { label: "Support Level", value: "Medium" },
      { label: "Features", value: "Moisture-wicking, Removable pads" },
      { label: "Care", value: "Machine wash cold, hang dry" },
    ],
  },
  {
    _id: "espson2",
    img : {spfOne } , productName :"Athletic Tank Top",
    price: "26.00",
    color: "White",
    badge: true,
    brand: "ActiveWear",
    des: "Lightweight athletic tank - Breathable mesh panels - Moisture-wicking fabric - Racerback design - Perfect for running and gym",
    cat: "Activewear",
    pdf: "pdf1",
    ficheTech: [
      { label: "Material", value: "92% Polyester, 8% Spandex" },
      { label: "Features", value: "Moisture-wicking, Breathable" },
      { label: "Fit", value: "Slim fit" },
      { label: "Care", value: "Machine wash cold" },
    ],
  },
];